### ISSUE TITLE
_undefined_ method 'snapshot_id' for `nil:NilClass`

### ISSUE THREAD

**Issue by lloydwatkin** [KentaaNL/capistrano-asg-rolling#2]
```bash
Stopping instance(s)...
Creating AMI(s)...
 Updating Launch Template(s) with the new AMI(s)...
Triggering Instance Refresh on Auto Scaling Group(s)...
Successfully started Instance Refresh on Auto Scaling Group core-api-sidekiq-production.
Cleaning up old Launch Template version(s) and AMI(s)...
Deleting Launch Template core-api-production-sidekiq version 9...
Deleting AMI ami-098bfb70b1f09ebab and snapshots...
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `snapshot_id' for nil:NilClass

Tasks: TOP => rolling:cleanup
(See full trace by running task with --trace)
The deploy has failed with an error: undefined method `snapshot_id' for nil:NilClass
```

We've just started hitting this error on deploy after an amazingly smooth and effective integration. It looks like [the issue is here](https://github.com/KentaaNL/capistrano-asg-rolling/blob/4042c225c03abbd13cba814defc999f49404c324/lib/capistrano/asg/rolling/ami.rb#L64). Would this be safe to add a get out in case the value doesn't exist?

**Comment by ppostma** [comment]
Thanks for the feedback, we appreciate it! Nice to hear that the integration went so smooth.

I've pushed a new release to rubygems with the fix.
