### ISSUE TITLE
Add instances to ALB when only refresh instances are done

### ISSUE THREAD

**Issue by thamdavies** [KentaaNL/capistrano-asg-rolling#5]
Hi there, how to wait for `refresh instances` status to be done to add instances to ALB? if not, the end-user can use my system both the old version and the new version after deploying code.
Thanks.

**Comment by ppostma** [comment]
I think what you want is called [Blue/green deployments](https://docs.aws.amazon.com/whitepapers/latest/overview-deployment-options/bluegreen-deployments.html). This is as far as I know not supported by ASG Instance Refresh, which uses the rolling deployment strategy.

You can however lower the refresh settings like "minimum healthy percentage" and "instance warmup" to minimize the window of having multiple versions of the code live.

**Comment by thamdavies** [comment]
@ppostma This really help me, thank you very much.
